export const RECEIVE_TODOS = 'receive_todos'
export const ADD_TODO = 'add_todo'
export const REMOVE_TODO = 'remove_todo'
export const SELECT_ALL = 'select_all'
export const CLEAR_COMPLETED_TODOS = 'clear_completed_todos'